name: Build and Release

on:
  push:
    tags:
      - 'v*'
    branches:
      - '**'
  pull_request:

permissions:
  contents: write
  id-token: write
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.23.3

      - name: Build
        if: ${{ github.ref_type != 'tag' }}
        uses: goreleaser/goreleaser-action@v5
        with:
          version: latest
          args: build --clean --snapshot

      - name: Build
        if: ${{ github.ref_type == 'tag' }}
        uses: goreleaser/goreleaser-action@v5
        with:
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Artifacts (for non-tag builds)
        if: ${{ github.ref_type != 'tag' }}
        uses: actions/upload-artifact@v4
        with:
          name: built-binaries
          path: dist/*
