name: Build and Release

on:
  push:
    tags:
      - 'v*'
    branches:
      - '**'
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.23.3

      - name: Install GoReleaser
        uses: goreleaser/goreleaser-action@v5
        with:
          version: latest

      - name: Build or Release
        run: |
          if [[ "${GITHUB_REF}" == refs/tags/v* ]]; then
            echo "📦 Releasing version ${GITHUB_REF_NAME}"
            goreleaser release --clean
          else
            echo "🔨 Building snapshot (no release)"
            goreleaser build --clean --snapshot
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Artifacts (for non-tag builds)
        if: ${{ github.ref_type != 'tag' }}
        uses: actions/upload-artifact@v4
        with:
          name: built-binaries
          path: dist/*
